// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPageMain;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_ContUSS;
lv_obj_t * ui_lblUSS;
lv_obj_t * ui_lblUSSValue;
void ui_event_swUSS(lv_event_t * e);
lv_obj_t * ui_swUSS;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label9;
lv_obj_t * ui_lblHum;
lv_obj_t * ui_lblTemp;
lv_obj_t * ui_Container4;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_lblRSSI;
lv_obj_t * ui_lblMsg;
lv_obj_t * ui_TabPageGraph;
lv_obj_t * ui_TabPageAudio;
void ui_event_sldVolume(lv_event_t * e);
lv_obj_t * ui_sldVolume;
lv_obj_t * ui_lblVolumeValue;
void ui_event_SwPlayMusic(lv_event_t * e);
lv_obj_t * ui_SwPlayMusic;
lv_obj_t * ui_lblVolume;
lv_obj_t * ui_lblMusic;
lv_obj_t * ui_lblFreq;
void ui_event_sldFreq(lv_event_t * e);
lv_obj_t * ui_sldFreq;
lv_obj_t * ui_lblFreqValue;
lv_obj_t * ui_lblMarioMusic1;
void ui_event_SwPlayFreq(lv_event_t * e);
lv_obj_t * ui_SwPlayFreq;
lv_obj_t * ui_lblPlayWavMusic;
void ui_event_SwPlayWavMusic(lv_event_t * e);
lv_obj_t * ui_SwPlayWavMusic;
lv_obj_t * ui_TabPageSetting;
lv_obj_t * ui_DarkModeCont;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_lblDarkMode;
lv_obj_t * ui_BackLigthCont;
lv_obj_t * ui_lblBacklight;
lv_obj_t * ui_lblManual;
lv_obj_t * ui_lblPer;
lv_obj_t * ui_lblAutomatic;
void ui_event_switchManualAutomatic(lv_event_t * e);
lv_obj_t * ui_switchManualAutomatic;
void ui_event_LigthSensorSlider(lv_event_t * e);
lv_obj_t * ui_LigthSensorSlider;
lv_obj_t * ui_lblLigthSensorSliderValue;
lv_obj_t * ui_lblLigthSensor;
lv_obj_t * ui_lblLigthSensorValue;
lv_obj_t * ui_ResetCont1;
lv_obj_t * ui_lblSWReset;
void ui_event_btnReset(lv_event_t * e);
lv_obj_t * ui_btnReset;
lv_obj_t * ui_lblResetBtn;
lv_obj_t * ui_TabPageAbout;
lv_obj_t * ui_Container1;
lv_obj_t * ui_BuildDate;
lv_obj_t * ui_BuildDateValue;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Version;
lv_obj_t * ui_VerValue;
lv_obj_t * ui_Container3;
lv_obj_t * ui_lblRuntime;
lv_obj_t * ui_lblRuntimeYDValue;
lv_obj_t * ui_lblRuntimeHMSValue;
lv_obj_t * ui_Spinner1;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Time;
lv_obj_t * ui_Panel2;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label2;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label3;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_SliderValue;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Label10;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Image1;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Spinbox2;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Button3;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_TabPage4;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_TabPage6;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_Chart3;
lv_obj_t * ui_Chart3_Xaxis;
lv_obj_t * ui_Chart3_Yaxis1;
lv_obj_t * ui_Chart3_Yaxis2;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_2145468593[1] = {&ui_img_1470329140};
const lv_image_dsc_t * ui_imgset_2059797558[1] = {&ui_img_1331304740};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_swUSS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcUSSenable(e);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}
void ui_event_sldVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblVolumeValue, target, "", "%");
        funcVolume(e);
    }
}
void ui_event_SwPlayMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcPlayMusic(e);
    }
}
void ui_event_sldFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblFreqValue, target, "", "Hz");
        func_FreqSlider(e);
    }
}
void ui_event_SwPlayFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcPlayFreq(e);
    }
}
void ui_event_SwPlayWavMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcPlayWavMusic(e);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DARK);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DEFAULT);
    }
}
void ui_event_switchManualAutomatic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcManualAutomatic(e);
    }
}
void ui_event_LigthSensorSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblLigthSensorSliderValue, target, "", "%");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcSetBackLight(e);
    }
}
void ui_event_btnReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        funcReset(e);
        (e);
    }
}
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        CounterAdd(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ToogleValue(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderValue, target, "", "%");
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
