// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#ifndef _SQUARELINE_PROJECT_TEST2_UI_H
#define _SQUARELINE_PROJECT_TEST2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPageMain;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_ContUSS;
extern lv_obj_t * ui_lblUSS;
extern lv_obj_t * ui_lblUSSValue;
void ui_event_swUSS(lv_event_t * e);
extern lv_obj_t * ui_swUSS;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_lblHum;
extern lv_obj_t * ui_lblTemp;
extern lv_obj_t * ui_Container4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_lblRSSI;
extern lv_obj_t * ui_lblMsg;
extern lv_obj_t * ui_TabPageGraph;
extern lv_obj_t * ui_TabPageAudio;
void ui_event_sldVolume(lv_event_t * e);
extern lv_obj_t * ui_sldVolume;
extern lv_obj_t * ui_lblVolumeValue;
void ui_event_SwPlayMusic(lv_event_t * e);
extern lv_obj_t * ui_SwPlayMusic;
extern lv_obj_t * ui_lblVolume;
extern lv_obj_t * ui_lblMusic;
extern lv_obj_t * ui_lblFreq;
void ui_event_sldFreq(lv_event_t * e);
extern lv_obj_t * ui_sldFreq;
extern lv_obj_t * ui_lblFreqValue;
extern lv_obj_t * ui_lblMarioMusic1;
void ui_event_SwPlayFreq(lv_event_t * e);
extern lv_obj_t * ui_SwPlayFreq;
extern lv_obj_t * ui_lblPlayWavMusic;
void ui_event_SwPlayWavMusic(lv_event_t * e);
extern lv_obj_t * ui_SwPlayWavMusic;
extern lv_obj_t * ui_TabPageSetting;
extern lv_obj_t * ui_DarkModeCont;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_lblDarkMode;
extern lv_obj_t * ui_BackLigthCont;
extern lv_obj_t * ui_lblBacklight;
extern lv_obj_t * ui_lblManual;
extern lv_obj_t * ui_lblPer;
extern lv_obj_t * ui_lblAutomatic;
void ui_event_switchManualAutomatic(lv_event_t * e);
extern lv_obj_t * ui_switchManualAutomatic;
void ui_event_LigthSensorSlider(lv_event_t * e);
extern lv_obj_t * ui_LigthSensorSlider;
extern lv_obj_t * ui_lblLigthSensorSliderValue;
extern lv_obj_t * ui_lblLigthSensor;
extern lv_obj_t * ui_lblLigthSensorValue;
extern lv_obj_t * ui_ResetCont1;
extern lv_obj_t * ui_lblSWReset;
void ui_event_btnReset(lv_event_t * e);
extern lv_obj_t * ui_btnReset;
extern lv_obj_t * ui_lblResetBtn;
extern lv_obj_t * ui_TabPageAbout;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_BuildDate;
extern lv_obj_t * ui_BuildDateValue;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Version;
extern lv_obj_t * ui_VerValue;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_lblRuntime;
extern lv_obj_t * ui_lblRuntimeYDValue;
extern lv_obj_t * ui_lblRuntimeHMSValue;
extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Panel2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_SliderValue;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Label10;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Spinbox2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_TabPage6;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1331304740);    // assets/2024-10-22_13h54_29.png
LV_IMG_DECLARE(ui_img_1470329140);    // assets/2024-10-11_16h32_35.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
