// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void funcUSSenable(lv_event_t * e);
void funcVolume(lv_event_t * e);
void funcPlayMusic(lv_event_t * e);
void func_FreqSlider(lv_event_t * e);
void funcPlayFreq(lv_event_t * e);
void funcPlayWavMusic(lv_event_t * e);
void funcManualAutomatic(lv_event_t * e);
void funcSetBackLight(lv_event_t * e);
void funcReset(lv_event_t * e);
void CounterAdd(lv_event_t * e);
void ToogleValue(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
