// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#include "ui.h"
#include <Arduino.h>
#include <math.h>

void CounterAdd(lv_event_t * e)
{
	// Your code here123
	static uint32_t cnt = 0;
    cnt++;
    lv_label_set_text_fmt(ui_Label4, "%u", cnt);
}

void ToogleValue(lv_event_t * e)
{
	static bool toogle_Value = 0;
    toogle_Value=!toogle_Value;
    lv_label_set_text_fmt(ui_Label6, "%d", toogle_Value);
}




