// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);

    ui_TabView2 = lv_tabview_create(ui_MainScreen);
    lv_tabview_set_tab_bar_size(ui_TabView2, 20);
    lv_obj_set_width(ui_TabView2, 318);
    lv_obj_set_height(ui_TabView2, 220);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 10);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TabView2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_TabView2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_TabView2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_TabView2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_TabView2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView2),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView2),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_FontColor);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView2),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView2),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BackGround);

    ui_TabPageMain = lv_tabview_add_tab(ui_TabView2, "Main");

    ui_Panel4 = lv_obj_create(ui_TabPageMain);
    lv_obj_set_width(ui_Panel4, 316);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 48);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);

    ui_ContUSS = lv_obj_create(ui_TabPageMain);
    lv_obj_remove_style_all(ui_ContUSS);
    lv_obj_set_width(ui_ContUSS, 316);
    lv_obj_set_height(ui_ContUSS, 50);
    lv_obj_set_align(ui_ContUSS, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ContUSS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_ContUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_ContUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContUSS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUSS = lv_label_create(ui_ContUSS);
    lv_obj_set_width(ui_lblUSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblUSS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblUSS, "Distance:");
    ui_object_set_themeable_style_property(ui_lblUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblUSS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblUSSValue = lv_label_create(ui_ContUSS);
    lv_obj_set_width(ui_lblUSSValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUSSValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblUSSValue, -70);
    lv_obj_set_y(ui_lblUSSValue, 0);
    lv_obj_set_align(ui_lblUSSValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblUSSValue, "Disabled!");
    ui_object_set_themeable_style_property(ui_lblUSSValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblUSSValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_swUSS = lv_switch_create(ui_ContUSS);
    lv_obj_set_width(ui_swUSS, 50);
    lv_obj_set_height(ui_swUSS, 25);
    lv_obj_set_x(ui_swUSS, -11);
    lv_obj_set_y(ui_swUSS, 0);
    lv_obj_set_align(ui_swUSS, LV_ALIGN_RIGHT_MID);


    ui_Container6 = lv_obj_create(ui_TabPageMain);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 316);
    lv_obj_set_height(ui_Container6, 50);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 49);
    lv_obj_set_align(ui_Container6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -1);
    lv_obj_set_align(ui_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label9, "Temperature:\nHumidity:");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblHum = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHum, -70);
    lv_obj_set_y(ui_lblHum, 10);
    lv_obj_set_align(ui_lblHum, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblHum, "999.99 %");

    ui_lblTemp = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemp, -70);
    lv_obj_set_y(ui_lblTemp, -10);
    lv_obj_set_align(ui_lblTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblTemp, "99.99 °C");

    ui_Container4 = lv_obj_create(ui_TabPageMain);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 100);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 200);
    lv_obj_set_align(ui_Container4, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_TabPageMain);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, -98);
    lv_obj_set_y(ui_Button4, 55);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_TabPageMain);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -16);
    lv_obj_set_y(ui_Label14, 37);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "MSG:");

    ui_Label15 = lv_label_create(ui_TabPageMain);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -15);
    lv_obj_set_y(ui_Label15, 68);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "RSSI:");

    ui_lblRSSI = lv_label_create(ui_TabPageMain);
    lv_obj_set_width(ui_lblRSSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRSSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRSSI, 78);
    lv_obj_set_y(ui_lblRSSI, 70);
    lv_obj_set_align(ui_lblRSSI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRSSI, "text");

    ui_lblMsg = lv_label_create(ui_TabPageMain);
    lv_obj_set_width(ui_lblMsg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMsg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMsg, 77);
    lv_obj_set_y(ui_lblMsg, 37);
    lv_obj_set_align(ui_lblMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMsg, "text");

    ui_TabPageGraph = lv_tabview_add_tab(ui_TabView2, "Graph");

    ui_TabPageAudio = lv_tabview_add_tab(ui_TabView2, "Audio");

    ui_sldVolume = lv_slider_create(ui_TabPageAudio);
    lv_slider_set_value(ui_sldVolume, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sldVolume, 197);
    lv_obj_set_height(ui_sldVolume, 16);
    lv_obj_set_x(ui_sldVolume, 42);
    lv_obj_set_y(ui_sldVolume, -70);
    lv_obj_set_align(ui_sldVolume, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldVolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldVolume,
                                                                                                lv_obj_get_style_pad_right(ui_sldVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblVolumeValue = lv_label_create(ui_sldVolume);
    lv_obj_set_width(ui_lblVolumeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVolumeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblVolumeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVolumeValue, "5%");
    ui_object_set_themeable_style_property(ui_lblVolumeValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblVolumeValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_SwPlayMusic = lv_switch_create(ui_TabPageAudio);
    lv_obj_set_width(ui_SwPlayMusic, 50);
    lv_obj_set_height(ui_SwPlayMusic, 25);
    lv_obj_set_x(ui_SwPlayMusic, 67);
    lv_obj_set_y(ui_SwPlayMusic, 28);
    lv_obj_set_align(ui_SwPlayMusic, LV_ALIGN_CENTER);


    ui_lblVolume = lv_label_create(ui_TabPageAudio);
    lv_obj_set_width(ui_lblVolume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVolume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVolume, -119);
    lv_obj_set_y(ui_lblVolume, -70);
    lv_obj_set_align(ui_lblVolume, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVolume, "Volume:");
    ui_object_set_themeable_style_property(ui_lblVolume, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblVolume, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMusic = lv_label_create(ui_TabPageAudio);
    lv_obj_set_width(ui_lblMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMusic, -87);
    lv_obj_set_y(ui_lblMusic, 28);
    lv_obj_set_align(ui_lblMusic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMusic, "Play 8bit Music:");

    ui_lblFreq = lv_label_create(ui_TabPageAudio);
    lv_obj_set_width(ui_lblFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFreq, -129);
    lv_obj_set_y(ui_lblFreq, -41);
    lv_obj_set_align(ui_lblFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFreq, "Freq:");
    ui_object_set_themeable_style_property(ui_lblFreq, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblFreq, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_sldFreq = lv_slider_create(ui_TabPageAudio);
    lv_slider_set_range(ui_sldFreq, 20, 10000);
    lv_slider_set_value(ui_sldFreq, 1500, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldFreq) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldFreq, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sldFreq, 212);
    lv_obj_set_height(ui_sldFreq, 13);
    lv_obj_set_x(ui_sldFreq, 37);
    lv_obj_set_y(ui_sldFreq, -39);
    lv_obj_set_align(ui_sldFreq, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldFreq, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldFreq,
                                                                                              lv_obj_get_style_pad_right(ui_sldFreq, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblFreqValue = lv_label_create(ui_sldFreq);
    lv_obj_set_width(ui_lblFreqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFreqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblFreqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFreqValue, "1500 Hz");
    ui_object_set_themeable_style_property(ui_lblFreqValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblFreqValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMarioMusic1 = lv_label_create(ui_TabPageAudio);
    lv_obj_set_width(ui_lblMarioMusic1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMarioMusic1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMarioMusic1, -111);
    lv_obj_set_y(ui_lblMarioMusic1, -4);
    lv_obj_set_align(ui_lblMarioMusic1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMarioMusic1, "Play Freq");

    ui_SwPlayFreq = lv_switch_create(ui_TabPageAudio);
    lv_obj_set_width(ui_SwPlayFreq, 50);
    lv_obj_set_height(ui_SwPlayFreq, 25);
    lv_obj_set_x(ui_SwPlayFreq, 68);
    lv_obj_set_y(ui_SwPlayFreq, -8);
    lv_obj_set_align(ui_SwPlayFreq, LV_ALIGN_CENTER);


    ui_lblPlayWavMusic = lv_label_create(ui_TabPageAudio);
    lv_obj_set_width(ui_lblPlayWavMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPlayWavMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPlayWavMusic, -87);
    lv_obj_set_y(ui_lblPlayWavMusic, 59);
    lv_obj_set_align(ui_lblPlayWavMusic, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPlayWavMusic, "Play Wav Music:");

    ui_SwPlayWavMusic = lv_switch_create(ui_TabPageAudio);
    lv_obj_set_width(ui_SwPlayWavMusic, 50);
    lv_obj_set_height(ui_SwPlayWavMusic, 25);
    lv_obj_set_x(ui_SwPlayWavMusic, 67);
    lv_obj_set_y(ui_SwPlayWavMusic, 60);
    lv_obj_set_align(ui_SwPlayWavMusic, LV_ALIGN_CENTER);


    ui_TabPageSetting = lv_tabview_add_tab(ui_TabView2, "Settings");

    ui_DarkModeCont = lv_obj_create(ui_TabPageSetting);
    lv_obj_remove_style_all(ui_DarkModeCont);
    lv_obj_set_width(ui_DarkModeCont, 316);
    lv_obj_set_height(ui_DarkModeCont, 30);
    lv_obj_set_x(ui_DarkModeCont, 0);
    lv_obj_set_y(ui_DarkModeCont, -10);
    lv_obj_set_align(ui_DarkModeCont, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_DarkModeCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_DarkModeCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_DarkModeCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_DarkModeCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_DarkModeCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_DarkModeCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_DarkModeCont);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_x(ui_Switch1, -10);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);


    ui_lblDarkMode = lv_label_create(ui_DarkModeCont);
    lv_obj_set_width(ui_lblDarkMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDarkMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDarkMode, 10);
    lv_obj_set_y(ui_lblDarkMode, 0);
    lv_obj_set_align(ui_lblDarkMode, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblDarkMode, "Dark Mode:");
    ui_object_set_themeable_style_property(ui_lblDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_BackLigthCont = lv_obj_create(ui_TabPageSetting);
    lv_obj_remove_style_all(ui_BackLigthCont);
    lv_obj_set_width(ui_BackLigthCont, 316);
    lv_obj_set_height(ui_BackLigthCont, 80);
    lv_obj_set_x(ui_BackLigthCont, 0);
    lv_obj_set_y(ui_BackLigthCont, 19);
    lv_obj_set_align(ui_BackLigthCont, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_BackLigthCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BackLigthCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_BackLigthCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_BackLigthCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_BackLigthCont, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_BackLigthCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBacklight = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblBacklight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBacklight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBacklight, 10);
    lv_obj_set_y(ui_lblBacklight, 5);
    lv_label_set_text(ui_lblBacklight, "BackLight:");
    ui_object_set_themeable_style_property(ui_lblBacklight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBacklight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblManual = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblManual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblManual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblManual, 110);
    lv_obj_set_y(ui_lblManual, 5);
    lv_label_set_text(ui_lblManual, "Manual");
    ui_object_set_themeable_style_property(ui_lblManual, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblManual, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblPer = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblPer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPer, 168);
    lv_obj_set_y(ui_lblPer, 5);
    lv_label_set_text(ui_lblPer, "/");

    ui_lblAutomatic = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblAutomatic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAutomatic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAutomatic, 175);
    lv_obj_set_y(ui_lblAutomatic, 5);
    lv_label_set_text(ui_lblAutomatic, "Automatic");

    ui_switchManualAutomatic = lv_switch_create(ui_BackLigthCont);
    lv_obj_set_width(ui_switchManualAutomatic, 50);
    lv_obj_set_height(ui_switchManualAutomatic, 20);
    lv_obj_set_x(ui_switchManualAutomatic, -10);
    lv_obj_set_y(ui_switchManualAutomatic, 3);
    lv_obj_set_align(ui_switchManualAutomatic, LV_ALIGN_TOP_RIGHT);


    ui_LigthSensorSlider = lv_slider_create(ui_BackLigthCont);
    lv_slider_set_value(ui_LigthSensorSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LigthSensorSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LigthSensorSlider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_LigthSensorSlider, 280);
    lv_obj_set_height(ui_LigthSensorSlider, 15);
    lv_obj_set_x(ui_LigthSensorSlider, 0);
    lv_obj_set_y(ui_LigthSensorSlider, 22);
    lv_obj_set_align(ui_LigthSensorSlider, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LigthSensorSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LigthSensorSlider,
                                                                                                        lv_obj_get_style_pad_right(ui_LigthSensorSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblLigthSensorSliderValue = lv_label_create(ui_LigthSensorSlider);
    lv_obj_set_width(ui_lblLigthSensorSliderValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLigthSensorSliderValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblLigthSensorSliderValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLigthSensorSliderValue, "100%");
    ui_object_set_themeable_style_property(ui_lblLigthSensorSliderValue, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLigthSensorSliderValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblLigthSensor = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblLigthSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLigthSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLigthSensor, 10);
    lv_obj_set_y(ui_lblLigthSensor, 25);
    lv_label_set_text(ui_lblLigthSensor, "LightSensor:");
    ui_object_set_themeable_style_property(ui_lblLigthSensor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLigthSensor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblLigthSensorValue = lv_label_create(ui_BackLigthCont);
    lv_obj_set_width(ui_lblLigthSensorValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLigthSensorValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLigthSensorValue, -40);
    lv_obj_set_y(ui_lblLigthSensorValue, 25);
    lv_obj_set_align(ui_lblLigthSensorValue, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblLigthSensorValue, "0");
    ui_object_set_themeable_style_property(ui_lblLigthSensorValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLigthSensorValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ResetCont1 = lv_obj_create(ui_TabPageSetting);
    lv_obj_remove_style_all(ui_ResetCont1);
    lv_obj_set_width(ui_ResetCont1, 316);
    lv_obj_set_height(ui_ResetCont1, 30);
    lv_obj_set_x(ui_ResetCont1, 0);
    lv_obj_set_y(ui_ResetCont1, 98);
    lv_obj_set_align(ui_ResetCont1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ResetCont1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ResetCont1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_ResetCont1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_ResetCont1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ResetCont1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ResetCont1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSWReset = lv_label_create(ui_ResetCont1);
    lv_obj_set_width(ui_lblSWReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSWReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSWReset, 10);
    lv_obj_set_y(ui_lblSWReset, 0);
    lv_obj_set_align(ui_lblSWReset, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblSWReset, "SW Reset:");
    ui_object_set_themeable_style_property(ui_lblSWReset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblSWReset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnReset = lv_button_create(ui_ResetCont1);
    lv_obj_set_width(ui_btnReset, 100);
    lv_obj_set_height(ui_btnReset, 25);
    lv_obj_set_x(ui_btnReset, 102);
    lv_obj_set_y(ui_btnReset, -1);
    lv_obj_set_align(ui_btnReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblResetBtn = lv_label_create(ui_btnReset);
    lv_obj_set_width(ui_lblResetBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblResetBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblResetBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblResetBtn, "RESET");

    ui_TabPageAbout = lv_tabview_add_tab(ui_TabView2, "About");

    ui_Container1 = lv_obj_create(ui_TabPageAbout);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 316);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuildDate = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_BuildDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BuildDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BuildDate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BuildDate, "BuildDate:");
    ui_object_set_themeable_style_property(ui_BuildDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_BuildDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_BuildDateValue = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_BuildDateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BuildDateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BuildDateValue, -5);
    lv_obj_set_y(ui_BuildDateValue, 0);
    lv_obj_set_align(ui_BuildDateValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BuildDateValue, "Oct 23 2024 12:22:36");
    ui_object_set_themeable_style_property(ui_BuildDateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_BuildDateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Container2 = lv_obj_create(ui_TabPageAbout);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 316);
    lv_obj_set_height(ui_Container2, 30);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 29);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Version = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Version, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Version, "Build Version:");
    ui_object_set_themeable_style_property(ui_Version, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Version, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_VerValue = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_VerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VerValue, -5);
    lv_obj_set_y(ui_VerValue, 0);
    lv_obj_set_align(ui_VerValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_VerValue, "99.99.999");
    ui_object_set_themeable_style_property(ui_VerValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_VerValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Container3 = lv_obj_create(ui_TabPageAbout);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 316);
    lv_obj_set_height(ui_Container3, 30);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 58);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRuntime = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblRuntime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRuntime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblRuntime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblRuntime, "Runtime:");
    ui_object_set_themeable_style_property(ui_lblRuntime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblRuntime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblRuntimeYDValue = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblRuntimeYDValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRuntimeYDValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRuntimeYDValue, 170);
    lv_obj_set_y(ui_lblRuntimeYDValue, -8);
    lv_obj_set_align(ui_lblRuntimeYDValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblRuntimeYDValue, "10 year 365 day");
    ui_object_set_themeable_style_property(ui_lblRuntimeYDValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblRuntimeYDValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblRuntimeYDValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRuntimeHMSValue = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblRuntimeHMSValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRuntimeHMSValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRuntimeHMSValue, 140);
    lv_obj_set_y(ui_lblRuntimeHMSValue, 8);
    lv_obj_set_align(ui_lblRuntimeHMSValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblRuntimeHMSValue, "24 hour 59 min 55.5 sec");
    ui_object_set_themeable_style_property(ui_lblRuntimeHMSValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblRuntimeHMSValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblRuntimeHMSValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_MainScreen);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 15);
    lv_obj_set_height(ui_Spinner1, 15);
    lv_obj_set_x(ui_Spinner1, -3);
    lv_obj_set_y(ui_Spinner1, 3);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swUSS, ui_event_swUSS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldVolume, ui_event_sldVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwPlayMusic, ui_event_SwPlayMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldFreq, ui_event_sldFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwPlayFreq, ui_event_SwPlayFreq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwPlayWavMusic, ui_event_SwPlayWavMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchManualAutomatic, ui_event_switchManualAutomatic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LigthSensorSlider, ui_event_LigthSensorSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReset, ui_event_btnReset, LV_EVENT_ALL, NULL);

}
