// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project_Test2

#include "../ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -10);
    lv_obj_set_y(ui_Label12, -43);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Temp [°C]");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label12, -900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 120);
    lv_obj_set_y(ui_Label13, -108);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Hum [%]");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x5900FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Label13, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label13, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 68);
    lv_obj_set_height(ui_Button5, 34);
    lv_obj_set_x(ui_Button5, -119);
    lv_obj_set_y(ui_Button5, -96);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_Screen4);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 15);
    lv_obj_set_height(ui_Spinner2, 15);
    lv_obj_set_x(ui_Spinner2, -3);
    lv_obj_set_y(ui_Spinner2, 3);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_Screen4);
    lv_obj_set_width(ui_Chart3, 247);
    lv_obj_set_height(ui_Chart3, 100);
    lv_obj_set_x(ui_Chart3, 0);
    lv_obj_set_y(ui_Chart3, 29);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart3, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart3, 50);
    lv_chart_set_div_line_count(ui_Chart3, 5, 5);

    ui_Chart3_Xaxis = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart3_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart3_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart3_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart3_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart3_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart3_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis1 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart3_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart3,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis2 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart3_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);



    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart3, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
